notion_documents = [
      {"clientName": "voluspa", "docId": "1KjyTZk1suvDlarlLSmNXQbE2JhlabDGhMPs7gFay_Kg"},
      {"clientName": "mymedic", "docId": "1XPuZqwMITL2khUXHqC8XrI45X-GtwctSO5Am8N2H-Bc"},
      {"clientName": "manlyman", "docId": "1uxmBY7zcpErNXAB0jamP1LEARsr3pzAOYwRjMggOYXg"},
      {"clientName": "jdsports", "docId": "1UIxZXgoqP8CRo6-_7sUVwjk4-BbgODKAbxPcoXqM8zc"},
      {"clientName": "malbongolf", "docId": "1eK3yaoC4dXPm8A7hdoPpsbBfjpY4vxcfKdmzJaPwlls"},
      {"clientName": "marijuana-packaging", "docId": "1johA13MY_0Kk-bHc8DHQ5XwyVx7LfInJRRl5STlh_W8"},
      {"clientName": "taosfootwear", "docId": "1ru8qf73Ok7cTB375drFy5lDWP4Eqd-qkNqm6DYPkwgg"},
      {"clientName": "shepherdsfashion", "docId": "10oSs_ngN0m6O4mrHcYU4vY6r5KLOBuCA5oXaObn6gPY"},
      {"clientName": "goldenlions", "docId": "18mewpwTQEE9PWKrZAXl_x5haX1KikK8dIf8L31LlsW4"},
      {"clientName": "fullglasswineco", "docId": "1iAQjRGAR5535WvQFfZPCe49jzVpubbgOzueeXoZfPcE"},
      {"clientName": "duck-camp", "docId": "1juTAGXE3SaESDCaxdvzGTDtCDRGjJfEgciCGvkLp4WA"},
      {"clientName": "emazing-group", "docId": "1PpajHpvp5cSjlEFQ8xJLRkjfeBZuQ7XIJG4SyJtvySM"},
      {"clientName": "silverfernbrand", "docId": "1i5jdZBi5DUEIJwWgTBB__o5_kGtp4baTXCG5H5AoZL4"},
      {"clientName": "darntough", "docId": "101d6uAMLpki3sOsiC-IkUewgBsXmZDCmBRP5OlqpTaQ"},
      {"clientName": "bartonwatches", "docId": "1TwrTnEAqQ3JLvfQ3InOQBmhei7gUzTLNDyyBQMtnIpI"},
      {"clientName": "hammitt", "docId": "10tHo4Wsb-zVTh_8ZbAqwKi1ljXjlaDvzEtmEYakw_1g"},
      {"clientName": "dermdude", "docId": "1U3sJmr7lFW5YN_x27AMs5NFNPQ4TNZCj-I2brpqhI6s"},
      {"clientName": "inprintwetrustt", "docId": "1LZj61i2ZRUB_bgC2AVzP7nsvuTxCMeATeQPwsw-oYDM"},
      {"clientName": "florida-premium-beef", "docId": "18cVAc75DQJHhR3CRLBJEoJivJ6jiVFoXfnvyxisxaYw"},
      {"clientName": "warroad", "docId": "1_9W9QmfvEV9mQFIPTty3NYGIkzfTZzxubym2ao969ww"},
      {"clientName": "tailwind-nutrition", "docId": "1PkvKj7oUaNjFtDkIhJ0GLtzzr3it3pprAJdUmluJCjU"},
      {"clientName": "printfresh", "docId": "1tXIT5gxiNpzBJB0har-mbJEKGJUcvYaxPThkZvjDao0"},
      {"clientName": "mindbodygreen", "docId": "1opRxaXGvWyke2IqLRpaWxOcqDMhmIMyigwu5p0O_hWo"},
      {"clientName": "shes-birdie", "docId": "1JEDy8KxcnI1BEMgR3fhY2wNpjKHNgUwu5U1wqUIdGNQ"},
      {"clientName": "axeandsledge", "docId": "1TKP5N_vcHmxvksuKJBX9MikZqsjfsd5zm4Zw3KdcaxY"},
      {"clientName": "heybud", "docId": "16oKaoAeq_-PzLDBjJzomnFV6qdWvC6c4jH8rm7aiP8I"},
      {"clientName": "jones-road", "docId": "1B6JO3SVwM-NlM2dMKh0ksXYLy4d5hIX5fPc4jEBhUis"},
      {"clientName": "createroom", "docId": "1LUuu5bQ8l6hY2sB2h3-TpXW-NUqAtsbcfC90tUgXGqo"},
      {"clientName": "choczero", "docId": "1x8aa0s3KLlEliSHz1j_POiuzHvaIUlMmGZmtYrX-nCQ"},
      {"clientName": "seekinghealth", "docId": "1d4ilnj3Sz66l7eJp7-792kFsNjtx56nXakt-Gsu6dkU"},
      {"clientName": "chefiq", "docId": "10jyj3MSCLVrkXx9Lr6uwwAv-wV5hkDRzODOgqJ1-goU"},
    ]
hubspot_documents = [
    # {"clientName": "voluspa", "docId": "1SzzRtWHsA4qqQ6Q-N7Puh-DsvsXPjFDRWhtS8u8PLsY"},
    # {"clientName": "mymedic", "docId": "1t4tJdU-NsvnTFkQJFKZRBwPAaI_hNsbVArSNStIq2dk"},
    # {"clientName": "manlyman", "docId": "16XpVRDlT8I0grBzyv1oVAHXX5R6ahX-NLj8XSfUhG8g"},
    # {"clientName": "jdsports", "docId": "1n1ST0x9xt81DJ5XhV026LGoMC0QUB8-u4YJztyOZA-M"},
    # {"clientName": "malbongolf", "docId": "1A-oPQEtFIkACdX4f96FkutvYtU118jx6Js76xFc69eA"},
    # {"clientName": "marijuana-packaging", "docId": "1oHrxFSulVtYmcG2b0oV6T6H6jX-gKiKHfafhQ5Mx6rA"},
    # {"clientName": "taosfootwear", "docId": "1M073iw-iwGHUV13ofkTeHTZ3v8jf59mc5_QTThabaYc"},
    # {"clientName": "shepherdsfashion", "docId": "1d-wlYmqXis6dAoS8fFLco8JKN00pS0JI5duEI0-17EM"},
    # {"clientName": "goldenlions", "docId": "1FHFG-wv1O3jkdH-rZU1uKh0RleRtYekymO0a7xTC0U4"},
    # {"clientName": "fullglasswineco", "docId": "19FucCr9tmydBxP9wQSZzbiKstCBBVyRXsvfEUlOgpM0"},
    # {"clientName": "duck-camp", "docId": "1XNzVS9-biKS-CeWdENCnkl6n4OEDoVGlqhcQzzbnnvQ"},
    # {"clientName": "emazing-group", "docId": "19EalaZPLEz5-pEx8wg68ygGc9menjOt3Pz0TnJGDr_M"},
    # {"clientName": "silverfernbrand", "docId": "1p7eqFiZZ4IEmNUx3dXtP9mgIqZU0a04l4PLnE5X9atM"},
    # {"clientName": "darntough", "docId": "11gZKIJUJCJ5A2hs-0Q86k0_4Wpt0klPC-ZXnQ-szny0"},
    # {"clientName": "bartonwatches", "docId": "1x7gYTy05cX20SreQPhM7UTlkiYjEuHdByEqvycDn68k"},
    # {"clientName": "hammitt", "docId": "1s_RPeOtX0RFVG7itF0dAx5x4i68yusFOAyBmH2FeAvk"},
    # {"clientName": "dermdude", "docId": "17_qW2bdjKo11Gf7UL53xtrxdRMNlvQBAHJEFD9b5JXE"},
    # {"clientName": "inprintwetrustt", "docId": "1_b6v78ONtKupGYD5e8yZUHYAxyjPwQzCoL1kRco46yU"},
    # {"clientName": "florida-premium-beef", "docId": "1JkIRDsqm_--sp-phaHea2M7uJ2HJMf-KGWhJGianS8c"},
    # {"clientName": "warroad", "docId": "1g5xYCuJ6SCL8P-CGd1428RFqrpxTAiLaLyWj4geLcjM"},
    # {"clientName": "tailwind-nutrition", "docId": "1eeItg3vkKvC8eFVUr8gR8t55Y32GAdjFYbfQyCZQ83A"},
    # {"clientName": "printfresh", "docId": "1WpEXv_IjonnrB7SzzQkiB3ZtGpAzOmKODHqfjOxqSZM"},
    # {"clientName": "mindbodygreen", "docId": "1ibPebFFQ_8PRjwbDecXISNP3XbL8jkxvb23XwNzQ47c"},
    # {"clientName": "shes-birdie", "docId": "1uyFBN-B-sKWVOe0T68JQ5YPMZb9vnewhHYXBbWLoGBU"},
    # {"clientName": "axeandsledge", "docId": "1sqPYcPnQMRM53sJ84GkmEnkFpGpef3va9GKX7kkaJHY"},
    # {"clientName": "heybud", "docId": "15nIRwwTStnzH1UvvRXWK9GZCxX4_iUihEksKw3RnMBk"},
    # {"clientName": "jones-road", "docId": "1_NZFQA7A76VyX9mjdISXkztdIS2WAsygOkcGPKmdQ70"},
    # {"clientName": "createroom", "docId": "1OBNLVmPObPbOmr2SaOgYIRbrIvyf0Iv2-DAe2DbsvXs"},
    # {"clientName": "choczero", "docId": "1XXwxTdiqJ61mKdRDc-797iO1xu2dyGrlQyvLRgxaDa8"},
    # {"clientName": "seekinghealth", "docId": "1uEDVWG5Bxnil1LlDhEzX9CU_hCQUdd_2m4hkpn7b1bQ"},
    # {"clientName": "javier", "docId": "1wbolZI-4j3J4K38bfSOqd-7FcMYo2KYp1S8a2L-0m6A"},
    # {"clientName": "ivycityco", "docId": "1cOJleDc1SF2nlmQS6hPVUn6lIXrRnZ4KTX6ygtrn-2o"},
    # {"clientName": "chefiq", "docId": "1n2bm7R8ktF_J2WQdbM7t3nT0MA7S0QEKiJLH6q6nsnA"},
    # {"clientName": "duck-camp", "docId": "1XNzVS9-biKS-CeWdENCnkl6n4OEDoVGlqhcQzzbnnvQ"},
    # {"clientName": "emazing-group", "docId": "19EalaZPLEz5-pEx8wg68ygGc9menjOt3Pz0TnJGDr_M"},
    # {"clientName": "inprintwetrustt", "docId": "1_b6v78ONtKupGYD5e8yZUHYAxyjPwQzCoL1kRco46yU"},
    # {"clientName": "florida-premium-beef", "docId": "1JkIRDsqm_--sp-phaHea2M7uJ2HJMf-KGWhJGianS8c"},
    # {"clientName": "warroad", "docId": "1g5xYCuJ6SCL8P-CGd1428RFqrpxTAiLaLyWj4geLcjM"},
    # {"clientName": "tailwind-nutrition", "docId": "1eeItg3vkKvC8eFVUr8gR8t55Y32GAdjFYbfQyCZQ83A"},
    # {"clientName": "printfresh", "docId": "1WpEXv_IjonnrB7SzzQkiB3ZtGpAzOmKODHqfjOxqSZM"},
    # {"clientName": "javier", "docId": "1ZB5HlvQPLWJjnTAqF7B0wqcsdNOexwtFU_HwEKtiVzI"},
    # {"clientName": "ivycityco", "docId": "1IFVUaQdbyHCIsrsJnDP4DRNvzm6upGSMOOu7LXcqheA"},
    # {"clientName": "chefiq", "docId": "1n2bm7R8ktF_J2WQdbM7t3nT0MA7S0QEKiJLH6q6nsnA"},


    ]
raw_messages_documents = [
    # {"clientName": "voluspa", "docId": "11mGn_sRZXGT5IGvbglefIxwSva2z6NYRJM0uS7pakhI"},
    # {"clientName": "mymedic", "docId": "1qPB4oF_SpQDBRN4fnH7RqM5A5O4B-sHC3KVb1_B7cMs"},
    # {"clientName": "shepherdsfashion", "docId": "1vnR8gIMsGMHRi8KzhMU5XJgwatX_mRs4t26dmvAl_bM"},
    # {"clientName": "manlyman", "docId": "19GQ67WmBuhtum6q-aBR4bTu5SfZqmGleIDiwcy67vek"},
    # {"clientName": "jdsports", "docId": "1lVH82TaVicGtQ_d6x4krhRsSDF4Ka20Hr929iU9mcbg"},
    # {"clientName": "malbongolf", "docId": "1u-MlKdFdsnGanmb2UPh15KRcp4UyQA6Kl53pEdtKcFU"},
    # {"clientName": "marijuana-packaging", "docId": "1nwkmdEVUQbQF76JLIYJVDrF_Kthj8VxKMdNINkwdP38"},
    # {"clientName": "taosfootwear", "docId": "1DUS3ZQZxp2Jraoe3z2cCcVBhJ38loRrHzLlW43TgQaM"},
    # {"clientName": "goldenlions", "docId": "1AS6y6klZ9bpNGqfyfe4jYhGmG_vriDWd-2nioITSm0Q"},
    # {"clientName": "fullglasswineco", "docId": "1Lrv-pY5hzCrnpBm9KQt4PAxtFM5RaaWmkVO45OT50bg"},
    # {"clientName": "silverfernbrand", "docId": "1ACP0Nqr5-HLjNvZEAB6w7ChgpZkMdOXZmwBBzpqBlhA"},
    # {"clientName": "bartonwatches", "docId": "1q3OkpiQmPhsktGT4d7gi1zSdpNK4_FK3g7rCTkqlBCE"},
    # {"clientName": "hammitt", "docId": "1xomungD8HjhplvznguVE2hb3tX5NDdU9Y62ohEK8v9k"},
    # {"clientName": "dermdude", "docId": "1tm_VMWGVYjN2HeGgyoy0e2sglXmwRXW9QMvlxiCQCDY"},
    # {"clientName": "mindbodygreen", "docId": "1s99FJGyuUsoymzvBcbwxnjS7hA1-kYm0AjGdgE1cu0I"},
    # {"clientName": "shes-birdie", "docId": "137ADTSwbB_wwJB557PXsTR9MwpZKsaOsGakwyTcsRoU"},
    # {"clientName": "axeandsledge", "docId": "1rSSkEminx9xU1KFJpzlyMd2n3T7h2lgYwIqUyHi6Axk"},
    # {"clientName": "jones-road", "docId": "1jzQHUNIUoizbVFRFOuucAi68wSgNH2DGayBwa-_9LG4"},
    # {"clientName": "createroom", "docId": "1HU55hQNb3i_2WQeMFqs7SFoRR_gcLVk14nYM0rtOtsM"},
    # {"clientName": "choczero", "docId": "1j_Jm7h6SnM-TosWxm56eas9CeCyoR_O0LUqoFs8erWI"},
    # {"clientName": "seekinghealth", "docId": "1hs_vTCMtU3OzxuY4BHPEuPZIxjAaONNX1IvcEU_NfVo"},
    # {"clientName": "javier", "docId": "1zi53vwSlXV4kaIkEk2TbcAjeolTrQJfD25o2iDam7eQ"},
    # {"clientName": "ivycityco", "docId": "1o8BTpVPxg32IOHhdJ-RCMndx8p-PUgNN9LOdfmp159k"},

    ]
transcript_documents = [
    # {"clientName": "voluspa", "docId": "1HqbkZymWgIM0i9H2y6g6v6nadxqugwBNURe9Zm8ZODk"},
    # {"clientName": "voluspa", "docId": "1xzYlbD0aolnZ14ZZ-BF7Z6Xb5TYEXaoiFkHk93hht5U"},
    # {"clientName": "mymedic", "docId": "1f48r_woNlO56dkZXyH56RGOWQp-HChALMyVZSqYvd9w"},
    # {"clientName": "shepherdsfashion", "docId": "1y0q4CIcusTLDEHBH6EhA3UkhFBPxp4x9QP2j4aBnQZ8"},
    # {"clientName": "manlyman", "docId": "1eax9yj6R6LELxlYE7ZUx_0a4T5WoPBxb-2qjgISeedk"},
    # {"clientName": "jdsports", "docId": "1lvDDA91jXMAWCE3qp2HE_mN0aDIvHHpq9RyalXE1j5Y"},
    # {"clientName": "malbongolf", "docId": "1yYYsIMzmMzay2zP5gDng8j6xFt3QPFLHcFZOdQO31gY"},
    # {"clientName": "marijuana-packaging", "docId": "10bIjxWGO9pwyDcYkgi1-T7Ium6KPMflc8pWrCgOPmoU"},
    # {"clientName": "taosfootwear", "docId": "1XQCRG9gwWz_Kkp_1nyyC-GdNcV9uULz6Hs_55lhRJAc"},
    # {"clientName": "taosfootwear", "docId": "1a2XROtg_gAlX9mxkqfE4gLm5DY6oDGzbAy-U51j9iUk"},
    # {"clientName": "goldenlions", "docId": "1Vk3kt4_g-SRNEF8I5EpRdRGsxwnNTi_nDuYsyM21Dvw"},
    # {"clientName": "fullglasswineco", "docId": "1kS2gEDwduniA3htKpbR8FyZnjD7yqUPnlXvlCbI5H1A"},
    # {"clientName": "silverfernbrand", "docId": "12UbT-vhyPUneWqYArqqait7jUEGcXfA4jkglwENTyAM"},
    # {"clientName": "bartonwatches", "docId": "1cBTmy_XLkYQybcafxyIHqg69fQCIBjeHhqncCHdfmCc"},
    # {"clientName": "hammitt", "docId": "19etcTKinNNK92FoaW8YO68cEoj_lhXT74EyUYt8vcrQ"},
    # {"clientName": "dermdude", "docId": "1ho9_UhYHQEWy6cdgOFi-WObiOtZcVTVzIKlAhN9dKKI"},
    # {"clientName": "mindbodygreen", "docId": "1jVpr_kMJUT2k_btL-CZAb5eNy49niJRaIgaGh7iyGZE"},
    # {"clientName": "shes-birdie", "docId": "1LxzpUZvehmcfaOhmc31gWsnih6d3PnRY8weYxnXCPdY"},
    # {"clientName": "axeandsledge", "docId": "1YS4CdaZh7JH7Tl-dp7sIvKTDygeyFUM92WE_CoRyDdw"},
    # {"clientName": "jones-road", "docId": "1EF7lOgvNWTBi0NGgF2lwkP5LrZ91hFDifa3SOHSM26Y"},
    # {"clientName": "createroom", "docId": "1i_oJ21menQ4sKYySicjCHrYMFgbzBZ-VpcSvY_jxm6Q"},
    # {"clientName": "choczero", "docId": "18bcIqEaIdEsWIM2H9ho6yoJU3TuoSf5V2gNtY5RWQrY"},
    # {"clientName": "seekinghealth", "docId": "1UJz_3Dac4TP7aorvc66ytaS2grG2-7jVROoNT94Yd64"},
    ]

faq_documents = [
    # {"clientName": "voluspa", "docId": "1o3o0DT5tmj0hkGtQtqVVP0Hb5YfhB1qY8zSWdstXJFc"},
    # {"clientName": "mymedic", "docId": "18qU1wIc-zgUjMGZHZBikBHfC9gPj61LdqpTY352JE7c"},
    # {"clientName": "shepherdsfashion", "docId": "1sjLJ1Gzufm09aMK2h3HkgWSFQMruLswPJRkmZL-itlA"},
    # {"clientName": "manlyman", "docId": "13JTmecjYAxb-LYBpaYDXr_yQObp-BUNdTPwG-Dtm1X8"},
    # {"clientName": "jdsports", "docId": "1UJZo9t6nofOhD7yk6sY_vYajKnoHNyI930DNgxv8rBo"},
    # {"clientName": "malbongolf", "docId": "1qqQ2RbIZ3Q1u-kxBRK932R0DR_dSHX2XJNIjlIZGzVU"},
    # {"clientName": "marijuana-packaging", "docId": "1T0P7GBE8jMwEp0c5ZcEPtLEg4-mfD8heIRvoLUlNsAg"},
    # {"clientName": "taosfootwear", "docId": "1B4nUSFzI-g5P1bL0B_JtUxbtx9B37xOmvm04GcsX7B8"},
    # {"clientName": "fullglasswineco", "docId": "1ZUxkirLZTnF1Ss0yjv5bVxwQjGx5hIUaniwWLoq9rRE"},
    # {"clientName": "silverfernbrand", "docId": "1CckdZapgZhEpFV4U7yBWRQi9mpcWfTcNxB-W80kdT28"},
    # {"clientName": "darntough", "docId": "19OkDfUZZgVfAnpJzsz6X2S9qUQBBLPmQe3RT8X53k7k"},
    # {"clientName": "hammitt", "docId": "1ycVodWDOWSQLwzXeMIivp_DcehM81sPArwSXks2mqK8"},
    # {"clientName": "dermdude", "docId": "1dTgFT4R_Guw1BfY--XmUpW6Hzjl8-f7txAQda2C56fE"},
    # {"clientName": "mindbodygreen", "docId": "1JYUnzJaU3nwEaErJ2Mdm3Ex5_odS_fMyvTiJGpVtvOU"},
    # {"clientName": "shes-birdie", "docId": "18djlDTg-ex403VkKhlyyvgoJ-8FmT2zXk_H9VnoS1eE"},
    # {"clientName": "axeandsledge", "docId": "1QnbAU9ATWRNtPZwpA7uwqSE5hN4TtIlvzAa1S8zUd8E"},
    # {"clientName": "jones-road", "docId": "1vKHdeAan0UuzK5pcdicx-8aTtU3slcXnv9PFrLfKtvw"},
    # {"clientName": "createroom", "docId": "1Cgc856szARGnQ5rv_HypXgiv520lxbvDuq0laTvlvww"},
    # {"clientName": "choczero", "docId": "1q0T6VOxsiBqq349DCXcsM2Y8suRuuEt_cN21LCZGUAc"},
    # {"clientName": "seekinghealth", "docId": "1j6w9aRqeGJn4Q1wE8_5svrkiUqQb1_XhmSvQ8TUJgB8"},
    # {"clientName": "javier", "docId": "1TROuglV-K44__q5wrib7Bj__wl-wKbvt0osgmumVhEU"},
    # {"clientName": "ivycityco", "docId": "1oigx5yS5O7TKpIcuL-u8i6VTXiWzrmcWQCuQXFb9d-M"},

    ]

internal_slack_messages_documents = [
    # {"clientName": "voluspa", "docId": "13p7D6v8oXhPmBhhwMyQcijm9E77oFA1T_11jcxJaEhM"},
    ]


documents = [

  ]